### ISSUE TITLE
有的重复项没有检测出来

### ISSUE THREAD

**Issue by Edger** [NMTuan/bitwarden_data#1]
如图，处理之后还是存在重复的

<img width="309" alt="image" src="https://user-images.githubusercontent.com/18591042/220987864-59268e3a-671e-4852-86d1-b32dbb4d0111.png">

**Comment by NMTuan** [comment]
会不会是url不完全一样？

目前查重机制是必须url地址完全一样。

**Comment by Edger** [comment]
> 会不会是url不完全一样？
> 
> 目前查重机制是必须url地址完全一样。

url 确实不一样，我改了一下代码，目前可以处理了
